// ============================================================
// App icon registry — Material icons (strict, app-wide).
// Registered once at the app root via provideIcons(). Keys MUST be the
// lowerCamelCase form of the name used in templates, because ng-icons
// resolves <ng-icon name="foo-bar"> through toPropertyName() → "fooBar"
// before looking the icon up. tp-icon passes its kebab `name` straight
// through, so e.g. name="check-square" resolves to the "checkSquare" key.
//
// All glyphs come from @ng-icons/material-icons (Google Material) so the
// whole UI uses one consistent, professional icon set.
// ============================================================
import {
  matGridView, matCheckBox, matCalendarToday, matFolder, matMemory,
  matBarChart, matMenu, matSearch, matAdd, matClose, matCheck,
  matLogin, matPersonAdd, matEdit, matDelete, matErrorOutline,
  matSchedule, matFlag, matSell, matLayers, matBolt, matTrendingUp,
  matGroup, matSend, matMic, matImage, matArrowForward, matArrowBack,
  matKeyboardArrowDown, matKeyboardArrowUp, matKeyboardArrowRight, matMoreHoriz,
  matFilterList, matRepeat, matLogout, matLightMode, matDarkMode, matSettings,
  matInbox, matList, matPlayCircle, matRadioButtonUnchecked, matDescription,
  matUpload, matLink, matContentCopy, matChatBubbleOutline, matChat,
  matFormatBold, matFormatItalic, matTextFields, matCheckCircle,
  matSubdirectoryArrowLeft, matAlternateEmail, matPerson, matCropSquare,
  matUndo, matRedo, matStar, matBookmark, matWork, matShield, matMail,
  matAutoAwesome, matDragIndicator,
} from '@ng-icons/material-icons/baseline';

/** camelCase key (== toPropertyName of the template name) → Material SVG. */
export const APP_ICONS: Record<string, string> = {
  grid:            matGridView,
  checkSquare:     matCheckBox,
  calendar:        matCalendarToday,
  folder:          matFolder,
  cpu:             matMemory,
  barChart2:       matBarChart,
  menu:            matMenu,
  search:          matSearch,
  plus:            matAdd,
  x:               matClose,
  check:           matCheck,
  logIn:           matLogin,
  userPlus:        matPersonAdd,
  edit2:           matEdit,
  trash2:          matDelete,
  alertCircle:     matErrorOutline,
  clock:           matSchedule,
  flag:            matFlag,
  tag:             matSell,
  layers:          matLayers,
  zap:             matBolt,
  trendingUp:      matTrendingUp,
  users:           matGroup,
  send:            matSend,
  mic:             matMic,
  image:           matImage,
  arrowRight:      matArrowForward,
  arrowLeft:       matArrowBack,
  chevronDown:     matKeyboardArrowDown,
  chevronUp:       matKeyboardArrowUp,
  chevronRight:    matKeyboardArrowRight,
  moreHorizontal:  matMoreHoriz,
  filter:          matFilterList,
  repeat:          matRepeat,
  logOut:          matLogout,
  sun:             matLightMode,
  moon:            matDarkMode,
  settings:        matSettings,
  inbox:           matInbox,
  sparkles:        matAutoAwesome,
  list:            matList,
  playCircle:      matPlayCircle,
  circle:          matRadioButtonUnchecked,
  fileText:        matDescription,
  upload:          matUpload,
  link:            matLink,
  copy:            matContentCopy,
  messageSquare:   matChatBubbleOutline,
  messageCircle:   matChat,
  bold:            matFormatBold,
  italic:          matFormatItalic,
  type:            matTextFields,
  checkCircle:     matCheckCircle,
  cornerDownLeft:  matSubdirectoryArrowLeft,
  atSign:          matAlternateEmail,
  user:            matPerson,
  square:          matCropSquare,
  rotateCcw:       matUndo,
  rotateCw:        matRedo,
  star:            matStar,
  bookmark:        matBookmark,
  briefcase:       matWork,
  shield:          matShield,
  mail:            matMail,
  drag:            matDragIndicator,
};
