// ============================================================
// App icon registry — powered by ng-icons (https://ng-icons.github.io).
// Icons are registered under the app's existing kebab-case names so every
// <tp-icon name="…"> keeps working; the SVGs now come from the Feather
// pack (@ng-icons/feather-icons), with Lucide filling the one gap Feather
// lacks (sparkles). Registered once at the app root via provideIcons().
// ============================================================
import {
  featherGrid, featherCheckSquare, featherCalendar, featherFolder, featherCpu,
  featherBarChart2, featherMenu, featherSearch, featherPlus, featherX, featherCheck,
  featherLogIn, featherUserPlus, featherEdit2, featherTrash2, featherAlertCircle,
  featherClock, featherFlag, featherTag, featherLayers, featherZap, featherTrendingUp,
  featherUsers, featherSend, featherMic, featherImage, featherArrowRight, featherArrowLeft,
  featherChevronDown, featherChevronUp, featherChevronRight, featherMoreHorizontal,
  featherFilter, featherRepeat, featherLogOut, featherSun, featherMoon, featherSettings,
  featherInbox, featherList, featherPlayCircle, featherCircle, featherFileText,
  featherUpload, featherLink, featherCopy, featherMessageSquare, featherMessageCircle,
  featherBold, featherItalic, featherType, featherCheckCircle, featherCornerDownLeft,
  featherAtSign, featherUser, featherSquare, featherRotateCcw, featherRotateCw,
  featherStar, featherBookmark,
} from '@ng-icons/feather-icons';
import { lucideSparkles } from '@ng-icons/lucide';

/** Kebab name → icon SVG. Keys match the names used across the app's templates. */
export const APP_ICONS: Record<string, string> = {
  'grid':            featherGrid,
  'check-square':    featherCheckSquare,
  'calendar':        featherCalendar,
  'folder':          featherFolder,
  'cpu':             featherCpu,
  'bar-chart-2':     featherBarChart2,
  'menu':            featherMenu,
  'search':          featherSearch,
  'plus':            featherPlus,
  'x':               featherX,
  'check':           featherCheck,
  'log-in':          featherLogIn,
  'user-plus':       featherUserPlus,
  'edit-2':          featherEdit2,
  'trash-2':         featherTrash2,
  'alert-circle':    featherAlertCircle,
  'clock':           featherClock,
  'flag':            featherFlag,
  'tag':             featherTag,
  'layers':          featherLayers,
  'zap':             featherZap,
  'trending-up':     featherTrendingUp,
  'users':           featherUsers,
  'send':            featherSend,
  'mic':             featherMic,
  'image':           featherImage,
  'arrow-right':     featherArrowRight,
  'arrow-left':      featherArrowLeft,
  'chevron-down':    featherChevronDown,
  'chevron-up':      featherChevronUp,
  'chevron-right':   featherChevronRight,
  'more-horizontal': featherMoreHorizontal,
  'filter':          featherFilter,
  'repeat':          featherRepeat,
  'log-out':         featherLogOut,
  'sun':             featherSun,
  'moon':            featherMoon,
  'settings':        featherSettings,
  'inbox':           featherInbox,
  'sparkles':        lucideSparkles,
  'list':            featherList,
  'play-circle':     featherPlayCircle,
  'circle':          featherCircle,
  'file-text':       featherFileText,
  'upload':          featherUpload,
  'link':            featherLink,
  'copy':            featherCopy,
  'message-square':  featherMessageSquare,
  'message-circle':  featherMessageCircle,
  'bold':            featherBold,
  'italic':          featherItalic,
  'type':            featherType,
  'check-circle':    featherCheckCircle,
  'corner-down-left':featherCornerDownLeft,
  'at-sign':         featherAtSign,
  'user':            featherUser,
  'square':          featherSquare,
  'rotate-ccw':      featherRotateCcw,
  'rotate-cw':       featherRotateCw,
  'star':            featherStar,
  'bookmark':        featherBookmark,
};
