// ============================================================
// AI Brief Models — shared shapes for the AI Dashboard layer.
// These describe natural-language productivity briefs generated by
// AiDashboardService (which reuses the existing `transformText` AI
// endpoint and always has a deterministic local fallback).
// ============================================================

export type AiBriefKind =
  | 'morning'      // Morning Brief
  | 'daily'        // Daily Summary
  | 'weekly'       // Weekly Summary
  | 'suggestions'  // Productivity Suggestions
  | 'focus'        // Focus Recommendation
  | 'risk';        // Risk Detection

/** A generated brief. `source` tells consumers whether AI or the local
 *  deterministic generator produced it (so the UI can badge it). */
export interface AiBrief {
  kind:        AiBriefKind;
  title:       string;
  /** Primary body text (plain text; may contain newlines). */
  text:        string;
  /** Bullet points parsed/derived from the body, for list rendering. */
  bullets:     string[];
  source:      'ai' | 'local';
  /** Epoch millis the brief was produced. */
  generatedAt: number;
}

export type RiskSeverity = 'warning' | 'critical';

/** A discrete, deterministically-detected productivity risk. */
export interface RiskFlag {
  id:       string;
  severity: RiskSeverity;
  title:    string;
  detail:   string;
  /** Ids of the tasks that triggered this risk (if applicable). */
  taskIds:  string[];
}
